#!/usr/bin/env python3
"""
Guardrail: no real song pack in committed files.

WHY THIS IS A PRIVACY CHECK
    A song pack is a song, measured: every band's level a hundred times a
    second, the loudness curve, the beat grid, the vocal's activity (see
    src/kaleidophone/audio/envelope.py). Made from an unreleased master, it is
    as private as the master (docs/decisions/0007-three-engines-one-contract.md,
    docs/decisions/0003-public-framework-private-assets.md). Nothing else here
    stops one: it is plain JSON, and a four-minute stereo song's pack is about
    1.6 MB (measured: `kaleidophone envelope` on a synthetic 240 s WAV), under
    check_no_media.sh's 2 MiB per-file ceiling. And it is easy to commit by
    accident: `kaleidophone envelope` writes ./songpack.json by default, and a
    pack is exactly what you copy next to a piece to render it.

    .gitignore refuses *songpack*.json. This refuses a pack whatever the file
    is called, including one that `git add -f` pushed past .gitignore.

    Pieces in this repository run on synthetic packs instead, generated by
    canvas/tools/synth.mjs from the piece's synthetic.json and marked
    "synthetic": true. A synthetic.json itself is not a pack -- the song's grid
    and rounded section levels, nothing measured frame by frame -- and passes.

WHAT IT CHECKS
    Every tracked text file. A JSON object is a song pack if it
      - carries the format tag "kaleidophone": "songpack/1", which is what
        `kaleidophone envelope` writes, or
      - has the shape of one: two or more envelope arrays (bass, mid, rms,
        flux, ...) of MIN_VALUES or more numbers. Packs made before
        `kaleidophone envelope` existed were hand-rolled per release and carry
        no tag; their data gives them away.
    A pack passes only if it says "synthetic": true.

    A file that isn't one JSON document -- a truncated excerpt, JSON lines, a
    pack pasted into source code -- is judged on its text: two envelope arrays
    of MIN_VALUES+ numbers anywhere, or the format tag in a file named .json,
    .jsonl or .ndjson, fail unless the file says "synthetic": true.

WHAT IT CANNOT CATCH
    A pack disguised on purpose: compressed, encoded, keys renamed. This check
    catches accidents; review catches the rest (CONTRIBUTING.md, item 5).

USAGE
    python3 check_no_real_songpacks.py
    Exit 0 if clean, 1 if a real song pack is tracked.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from collections.abc import Iterator

TAG = "songpack/1"

# Envelope names a pack carries, in either format (envelope.py's bands, flux
# envelopes, rms, cent and voc). `beats` is deliberately not one: a beat list
# also turns up in EDLs and briefs, which are nobody's secret.
ENVELOPES = ("bass", "lowmid", "mid", "high", "air", "rms", "flux", "bflux", "hflux", "cent", "voc")
MIN_VALUES = 100  # one second at the pack's 100 Hz
MIN_ENVELOPES = 2  # one long array could be anything; two named like bands is a song

DATA_SUFFIXES = (".json", ".jsonl", ".ndjson")

TAG_RE = re.compile(r'"kaleidophone"\s*:\s*"songpack/1"')
SYNTHETIC_RE = re.compile(r"""["']?\bsynthetic["']?\s*:\s*(?:true|True)\b""")
_KEY = r"""(?<![\w$])["']?(%s)["']?\s*:\s*\[""" % "|".join(ENVELOPES)
_NUM = r"\s*-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?\s*"
# Quoted or not: a pack pasted into JavaScript can lose its key quotes.
ENVELOPE_KEY_RE = re.compile(_KEY + r"\s*-?\d")
ENVELOPE_ARRAY_RE = re.compile(_KEY + r"(?:%s,){%d}%s[,\]]" % (_NUM, MIN_VALUES - 1, _NUM))

_NOT_JSON = object()


def tracked_files() -> list[str]:
    # -z: names exactly as stored, without git's quoting of unusual characters
    out = subprocess.run(["git", "ls-files", "-z"], capture_output=True, text=True, check=True).stdout
    return [f for f in out.split("\0") if f]


def count_numbers(value: object) -> int:
    if not isinstance(value, list):
        return 0
    return sum(1 for v in value if isinstance(v, (int, float)) and not isinstance(v, bool))


def why_a_pack(obj: dict) -> str | None:
    """Why `obj` is a song pack, or None if it isn't one."""
    if obj.get("kaleidophone") == TAG:
        return f'it carries the format tag "kaleidophone": "{TAG}"'
    envs = [k for k in ENVELOPES if count_numbers(obj.get(k)) >= MIN_VALUES]
    if len(envs) >= MIN_ENVELOPES:
        return f"{len(envs)} envelopes of {MIN_VALUES}+ values ({', '.join(envs)}): the shape of a pack"
    return None


def objects(doc: object) -> Iterator[tuple[str, dict]]:
    """Every JSON object in `doc`, with where it sits ($ is the whole file)."""
    stack = [("$", doc)]
    while stack:
        where, value = stack.pop()
        if isinstance(value, dict):
            yield where, value
            children = [(f"{where}.{k}", v) for k, v in value.items()]
        elif isinstance(value, list):
            children = [(f"{where}[{i}]", v) for i, v in enumerate(value)]
        else:
            continue
        stack.extend(reversed([c for c in children if isinstance(c[1], (dict, list))]))


def check_text(path: str, text: str) -> tuple[list[tuple[str, str]], int]:
    """(real packs as (where, why), synthetic packs seen) in one file's text."""
    try:
        doc = json.loads(text)
    except (ValueError, RecursionError):
        doc = _NOT_JSON

    real: list[tuple[str, str]] = []
    synthetic = 0
    if doc is not _NOT_JSON:
        for where, obj in objects(doc):
            why = why_a_pack(obj)
            if why is None:
                continue
            if obj.get("synthetic") is True:
                synthetic += 1
            else:
                real.append((where, why))
        return real, synthetic

    envs = sorted({m.group(1) for m in ENVELOPE_ARRAY_RE.finditer(text)})
    if len(envs) >= MIN_ENVELOPES:
        why = f"{len(envs)} envelopes of {MIN_VALUES}+ values ({', '.join(envs)}) in a file that isn't one JSON document"
    elif path.lower().endswith(DATA_SUFFIXES) and TAG_RE.search(text):
        why = f'the format tag "{TAG}" in a file that isn\'t valid JSON -- an excerpt of a pack is still the pack'
    else:
        return real, synthetic  # prose or code that only names the format
    if SYNTHETIC_RE.search(text):
        synthetic += 1
    else:
        real.append(("", why))
    return real, synthetic


def _escape(s: str, prop: bool = False) -> str:
    s = s.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
    return s.replace(":", "%3A").replace(",", "%2C") if prop else s


def main() -> int:
    real: list[tuple[str, str, str]] = []
    synthetic = 0

    for path in tracked_files():
        try:
            # utf-8-sig: a byte-order mark would otherwise make valid JSON unreadable
            with open(path, encoding="utf-8-sig", errors="strict") as fh:
                text = fh.read()
        except (UnicodeDecodeError, IsADirectoryError, FileNotFoundError):
            continue  # binary, a submodule, or deleted locally; check_no_media.sh covers binaries
        if not (TAG_RE.search(text) or ENVELOPE_KEY_RE.search(text)):
            continue
        found, seen = check_text(path, text)
        real.extend((path, where, why) for where, why in found)
        synthetic += seen

    for path, where, why in real:
        at = f" at {where}" if where not in ("", "$") else ""
        print(
            f"::error file={_escape(path, prop=True)}::"
            + _escape(
                f'A real song pack must not be committed{at}: {why}, and it isn\'t marked "synthetic": true.'
            )
        )
        print(f"  refused: {path}{at}  ({why})")

    if real:
        print(
            "\n"
            "  A song pack measured from a real song is private, like the audio it\n"
            "  came from (docs/decisions/0007-three-engines-one-contract.md). To fix:\n"
            "\n"
            "  1. Take it out of every commit on your branch, not just the last one\n"
            "     (git rm --cached <file>, then amend or rebase the commit that added\n"
            "     it), and keep real packs in a private/ folder, which .gitignore\n"
            "     ignores at any depth:\n"
            "         kaleidophone envelope song.wav -o private/songpack.json\n"
            "\n"
            "  2. If a piece needs the song's shape, commit its synthetic twin instead:\n"
            "         cd canvas && node tools/synth.mjs --twin ../private/songpack.json \\\n"
            "             --sections 0,32.26,42.26 > pieces/<id>/synthetic.json\n"
            '     See canvas/README.md, "Song packs: real ones stay private".\n'
            "\n"
            "  3. If it already reached main, deleting it in a later commit does not\n"
            "     remove it from history; that needs a history rewrite. Ask before\n"
            "     force-pushing.\n"
            "\n"
            "  If the pack really is synthetic -- generated, not measured from a\n"
            '  recording -- add "synthetic": true to it, as canvas/tools/synth.mjs does.\n'
        )
        return 1

    print(f"clean: no real song packs ({synthetic} synthetic pack(s) tracked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
